export enum ServerStatus {
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  SAVING_LOG = 'SAVING_LOG',
  SAVING_LOG_FAILED = 'SAVING_LOG_FAILED',
  SAVING_LOG_SUCCESS = 'SAVING_LOG_SUCCESS',
  READY_TO_DELETE = 'READY_TO_DELETE',
  DELETED = 'DELETED'
}