# Start with a base image of Java 21
FROM openjdk:21-jdk

# Set a working directory
WORKDIR /data/minecraft

# Set the startup command to run the jar file with the arguments read from the startscript.txt file
CMD java -jar velocity-3.3.0-SNAPSHOT-316.jar