package net.vellity.dynamic.servers.server.registry.http.client.dto

enum class UpdateType {
  STATUS_UPDATE_CREATED,
  STATUS_UPDATE_STARTING_TO_RUNNING,
  STATUS_UPDATE_RUNNING_TO_STOPPING,
  STATUS_UPDATE_REMOVED,
  STATUS_UPDATE_STOPPING_TO_STOPPED,
  STATUS_UPDATE_STOPPED_TO_SAVING_LOG,
  STATUS_UPDATE_SAVING_LOG_TO_SAVING_LOG_FAILED,
  STATUS_UPDATE_SAVING_LOG_TO_SAVING_LOG_SUCCESS,
  STATUS_UPDATE_TO_READY_TO_DELETE,
  STATUS_UPDATE_READY_TO_DELETE_TO_DELETED,
  TAGS_ELEMENT_ADDED
}